### ISSUE TITLE
MemN2NDialog.predict wrongly mix predictions

### ISSUE THREAD

**Issue by fdevillard** [fdevillard/personalized-dialog#1]
The predict method does not work as the combination of the models (shared/task-specific) appear to be wrong.

As to dig there to fix it.

**Comment by fdevillard** [comment]
```
(optsemproj) Florents-MacBook-Pro:MemN2N-mtl flo$ python single_dialog.py --epochs 1 --data_dir ../data/personalized-dial
og-dataset/small                                                                                                         
Started Task: 1                                                                                                          
/Users/flo/anaconda3/envs/optsemproj/lib/python3.6/re.py:212: FutureWarning: split() requires a non-empty pattern match. 
  return _compile(pattern, flags).split(string, maxsplit)                                                                
Candidate Size 43863                                                                                                     
Profiles: {('female', 'elderly'): 0, ('female', 'middle'): 1, ('female', 'young'): 2, ('male', 'elderly'): 3, ('male', 'm
iddle'): 4, ('male', 'young'): 5}                                                                                        
vocab size: 14590                                                                                                        
Longest sentence length 21                                                                                               
Longest candidate sentence length 13                                                                                     
Longest story length 15                                                                                                  
Average story length 6                                                                                                   
Training Size 6024                                                                                                       
Validation Size 6015                                                                                                     
Number of epochs: 1                                                                                                      
Epoch 1                                                                                                                  
[array([42346, 40778, 42346, 42346, 40778, 40778]), array([3220,  583,  583, 3220, 3220]), array([42346, 42346, 42346, 43
244, 36507]), array([32407, 11808, 11808, 11808, 18250, 11808, 18250, 18250]), array([3220,  583,  583,  583]), array([ 3
220, 42346, 42346, 42346])]                                                                                              
Traceback (most recent call last):                                                                                       
  File "single_dialog.py", line 260, in <module>                                                                         
    chatbot.train()                                                                                                      
  File "single_dialog.py", line 160, in train                                                                            
    train_preds=self.batch_predict(trainP, trainS, trainQ, n_train)                                                      
  File "single_dialog.py", line 213, in batch_predict                                                                    
    pred = self.model.predict(p, s, q)                                                                                   
  File "/Users/flo/Documents/Etudes/EPFL/ma5/optsemproj/personalized-dialog/MemN2N-mtl/memn2n/memn2n_dialog.py", line 415
, in predict                                                                                                           
    return np.mean(results)                                                                                            
  File "/Users/flo/anaconda3/envs/optsemproj/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2909, in mean
    out=out, **kwargs)                                                                                             
  File "/Users/flo/anaconda3/envs/optsemproj/lib/python3.6/site-packages/numpy/core/_methods.py", line 70, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims)                         
ValueError: operands could not be broadcast together with shapes (6,) (5,) 
```
